location: $LOCATION
name: $CONTAINER_NAME
resourceGroup: $RESOURCE_GROUP
properties:
  managedEnvironmentId: /subscriptions/$SUBSCRIPTION_ID$/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.App/managedEnvironments/$CONTAINER_APP_ENV
  configuration:
    activeRevisionsMode: Multiple
    secrets:
      - name: PINECONE_API_KEY
        value: $PINECONE_API_KEY
      - name: OPENAI_API_KEY
        value: $OPENAI_API_KEY
      - name: REGISTRY_PASSWORD
        value: $REGISTRY_PASSWORD
    ingress:
      external: true
      allowInsecure: true
      targetPort: 80
      traffic:
        - latestRevision: true
          weight: 100
      transport: Auto
    registries:
      - passwordSecretRef: REGISTRY_PASSWORD
        server: $REGISTRY_LOGIN_SERVER
        username: $REGISTRY_USERNAME
  template:
    containers:
      - image: $REGISTRY_LOGIN_SERVER$/$IMAGE_REPOSITORY:latest
        name: $CONTAINER_NAME
        resources:
          cpu: 1
          memory: 2Gi
        probes:
          - type: liveness
            httpGet:
              path: "/"
              port: 5000
            initialDelaySeconds: 7
            periodSeconds: 30
          - type: readiness
            tcpSocket:
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 30
    scale:
      minReplicas: 1
      maxReplicas: 2
