name: Deploy Bookalyze Backend

on:
  pull_request:

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Deploy to Azure Container Instances"
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: "ac-bookalyze-dev"
          appSourcePath: ${{ github.workspace }}/server
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          imageToBuild: ${{ env.REGISTRY_LOGIN_SERVER }}/bookalyze:latest
          registryUrl: ${{ env.REGISTRY_LOGIN_SERVER }}
          registryUsername: ${{ env.REGISTRY_USERNAME }}
          registryPassword: ${{ env.REGISTRY_PASSWORD }}
          environmentVariables: PINECONE_ENV=${{ secrets.PINECONE_ENV }} PINECONE_INDEX=${{ secrets.PINECONE_INDEX }} PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }} OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} FLASK_ENV=production
